### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by cryptozeny** [sugarchain-project/explorer#15]
> git clone https://github.com/sugarchain-project/explorer.git explorer && \
cd explorer && npm install --production

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/root/.nvm/v0.10.28/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/root/.nvm/v0.10.28/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /root/.nvm/v0.10.28/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Linux 4.4.0-141-generic
gyp ERR! command "node" "/root/.nvm/v0.10.28/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/explorer/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok 
npm http 200 https://registry.npmjs.org/ansi-font
npm http GET https://registry.npmjs.org/ansi-font/-/ansi-font-0.0.2.tgz
npm http 200 https://registry.npmjs.org/ansi-font/-/ansi-font-0.0.2.tgz

> kerberos@0.0.24 install /root/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/root/.nvm/v0.10.28/lib/node_modules/npm/node_modules/which/which.js:43:28)
gyp ERR! stack     at E (/root/.nvm/v0.10.28/lib/node_modules/npm/node_modules/which/which.js:46:29)
gyp ERR! stack     at /root/.nvm/v0.10.28/lib/node_modules/npm/node_modules/which/which.js:57:16
gyp ERR! stack     at Object.oncomplete (fs.js:107:15)
gyp ERR! System Linux 4.4.0-141-generic
gyp ERR! command "node" "/root/.nvm/v0.10.28/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/explorer/node_modules/mongoose/node_modules/mongodb/node_modules/mongodb-core/node_modules/kerberos
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok

**Comment by cryptozeny** [comment]
![image](https://user-images.githubusercontent.com/37016180/69223141-21fad580-0bbe-11ea-9546-4ecfda19797d.png)

![image](https://user-images.githubusercontent.com/37016180/69223158-2cb56a80-0bbe-11ea-9676-130cedac5f04.png)

**Comment by cryptozeny** [comment]
must install depends before

```
cd && \
sudo add-apt-repository ppa:bitcoin/bitcoin -y && \
sudo apt-get update -y && \
sudo apt-get install -y \
software-properties-common libdb4.8-dev libdb4.8++-dev build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils libboost-all-dev libminiupnpc-dev libzmq3-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev
```

closing
